name: example
description: An example app for drive_helper
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drive_helper:
    path: ../
  flutter_phoenix: ^1.0.0

flutter:
  uses-material-design: true
