name: drive_helper
description: An easy to use library for using Google Drive and Google sign in
version: 1.3.0
homepage: https://pub.dev/packages/drive_helper
repository: https://github.com/theRookieCoder/drive_helper

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.3.1
  googleapis: ^8.1.0
  http: ^0.13.4
  url_launcher: ^6.1.2
