name: drive_helper
description: An easy to use library for using Google Drive and Google sign in
version: 1.2.3
homepage: https://github.com/theRookieCoder/drive_helper
repository: https://github.com/theRookieCoder/drive_helper

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.2
  googleapis: ^2.0.0
  http: ^0.13.3
  url_launcher: ^6.0.3
